name: GH200-Workflow

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello to the GH-200 Workshop!!!"

      -  name: Copy Code
         uses: actions/checkout@v6

      -  name: List Repo Files
         run: ls -la

      - name: Create ASCII Art
        run: |
          sudo apt-get install -y figlet
          figlet "GH-200 COHACK"
          echo "--------------------------"
          figlet -f digital "GitHub Actions"
          echo "ASCII Art Generated"
